// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	ovs "github.com/k8snetworkplumbingwg/dra-driver-ovsdpdk/pkg/ovs"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockClient) Close() {
	_m.Called()
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return() *MockClient_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func()) *MockClient_Close_Call {
	_c.Run(run)
	return _c
}

// Connected provides a mock function with no fields
func (_m *MockClient) Connected() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connected")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockClient_Connected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connected'
type MockClient_Connected_Call struct {
	*mock.Call
}

// Connected is a helper method to define mock.On call
func (_e *MockClient_Expecter) Connected() *MockClient_Connected_Call {
	return &MockClient_Connected_Call{Call: _e.mock.On("Connected")}
}

func (_c *MockClient_Connected_Call) Run(run func()) *MockClient_Connected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Connected_Call) Return(_a0 bool) *MockClient_Connected_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Connected_Call) RunAndReturn(run func() bool) *MockClient_Connected_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePort provides a mock function with given fields: ctx, bridgeName, portName, socketPath, params
func (_m *MockClient) CreatePort(ctx context.Context, bridgeName string, portName string, socketPath string, params *ovs.OvsPortParams) error {
	ret := _m.Called(ctx, bridgeName, portName, socketPath, params)

	if len(ret) == 0 {
		panic("no return value specified for CreatePort")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *ovs.OvsPortParams) error); ok {
		r0 = rf(ctx, bridgeName, portName, socketPath, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_CreatePort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePort'
type MockClient_CreatePort_Call struct {
	*mock.Call
}

// CreatePort is a helper method to define mock.On call
//   - ctx context.Context
//   - bridgeName string
//   - portName string
//   - socketPath string
//   - params *ovs.OvsPortParams
func (_e *MockClient_Expecter) CreatePort(ctx interface{}, bridgeName interface{}, portName interface{}, socketPath interface{}, params interface{}) *MockClient_CreatePort_Call {
	return &MockClient_CreatePort_Call{Call: _e.mock.On("CreatePort", ctx, bridgeName, portName, socketPath, params)}
}

func (_c *MockClient_CreatePort_Call) Run(run func(ctx context.Context, bridgeName string, portName string, socketPath string, params *ovs.OvsPortParams)) *MockClient_CreatePort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(*ovs.OvsPortParams))
	})
	return _c
}

func (_c *MockClient_CreatePort_Call) Return(_a0 error) *MockClient_CreatePort_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_CreatePort_Call) RunAndReturn(run func(context.Context, string, string, string, *ovs.OvsPortParams) error) *MockClient_CreatePort_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePort provides a mock function with given fields: ctx, bridgeName, portName
func (_m *MockClient) DeletePort(ctx context.Context, bridgeName string, portName string) error {
	ret := _m.Called(ctx, bridgeName, portName)

	if len(ret) == 0 {
		panic("no return value specified for DeletePort")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, bridgeName, portName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_DeletePort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePort'
type MockClient_DeletePort_Call struct {
	*mock.Call
}

// DeletePort is a helper method to define mock.On call
//   - ctx context.Context
//   - bridgeName string
//   - portName string
func (_e *MockClient_Expecter) DeletePort(ctx interface{}, bridgeName interface{}, portName interface{}) *MockClient_DeletePort_Call {
	return &MockClient_DeletePort_Call{Call: _e.mock.On("DeletePort", ctx, bridgeName, portName)}
}

func (_c *MockClient_DeletePort_Call) Run(run func(ctx context.Context, bridgeName string, portName string)) *MockClient_DeletePort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_DeletePort_Call) Return(_a0 error) *MockClient_DeletePort_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_DeletePort_Call) RunAndReturn(run func(context.Context, string, string) error) *MockClient_DeletePort_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
