// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockSocketFS is an autogenerated mock type for the SocketFS type
type MockSocketFS struct {
	mock.Mock
}

type MockSocketFS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSocketFS) EXPECT() *MockSocketFS_Expecter {
	return &MockSocketFS_Expecter{mock: &_m.Mock}
}

// CreateSocketDir provides a mock function with given fields: path
func (_m *MockSocketFS) CreateSocketDir(path string) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for CreateSocketDir")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSocketFS_CreateSocketDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSocketDir'
type MockSocketFS_CreateSocketDir_Call struct {
	*mock.Call
}

// CreateSocketDir is a helper method to define mock.On call
//   - path string
func (_e *MockSocketFS_Expecter) CreateSocketDir(path interface{}) *MockSocketFS_CreateSocketDir_Call {
	return &MockSocketFS_CreateSocketDir_Call{Call: _e.mock.On("CreateSocketDir", path)}
}

func (_c *MockSocketFS_CreateSocketDir_Call) Run(run func(path string)) *MockSocketFS_CreateSocketDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSocketFS_CreateSocketDir_Call) Return(_a0 error) *MockSocketFS_CreateSocketDir_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSocketFS_CreateSocketDir_Call) RunAndReturn(run func(string) error) *MockSocketFS_CreateSocketDir_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveSocketDir provides a mock function with given fields: path
func (_m *MockSocketFS) RemoveSocketDir(path string) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for RemoveSocketDir")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSocketFS_RemoveSocketDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveSocketDir'
type MockSocketFS_RemoveSocketDir_Call struct {
	*mock.Call
}

// RemoveSocketDir is a helper method to define mock.On call
//   - path string
func (_e *MockSocketFS_Expecter) RemoveSocketDir(path interface{}) *MockSocketFS_RemoveSocketDir_Call {
	return &MockSocketFS_RemoveSocketDir_Call{Call: _e.mock.On("RemoveSocketDir", path)}
}

func (_c *MockSocketFS_RemoveSocketDir_Call) Run(run func(path string)) *MockSocketFS_RemoveSocketDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSocketFS_RemoveSocketDir_Call) Return(_a0 error) *MockSocketFS_RemoveSocketDir_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSocketFS_RemoveSocketDir_Call) RunAndReturn(run func(string) error) *MockSocketFS_RemoveSocketDir_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSocketFS creates a new instance of MockSocketFS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSocketFS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSocketFS {
	mock := &MockSocketFS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
