apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: ovsdpdk-driver
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowHostNetwork: false
allowHostPorts: false
allowHostPID: true
allowHostIPC: false
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
  - hostPath
  - emptyDir
  - secret
users:
  - system:serviceaccount:dra-driver-ovsdpdk:dra-driver-ovsdpdk
