// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	devicestate "github.com/amorenoz/dra-driver-ovsdpdk/pkg/devicestate"
	mock "github.com/stretchr/testify/mock"

	types "github.com/amorenoz/dra-driver-ovsdpdk/pkg/types"

	v1 "k8s.io/api/resource/v1"
)

// MockDeviceStateIface is an autogenerated mock type for the DeviceStateIface type
type MockDeviceStateIface struct {
	mock.Mock
}

type MockDeviceStateIface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceStateIface) EXPECT() *MockDeviceStateIface_Expecter {
	return &MockDeviceStateIface_Expecter{mock: &_m.Mock}
}

// GetAllocatableDevices provides a mock function with no fields
func (_m *MockDeviceStateIface) GetAllocatableDevices() devicestate.AllocatableDevices {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllocatableDevices")
	}

	var r0 devicestate.AllocatableDevices
	if rf, ok := ret.Get(0).(func() devicestate.AllocatableDevices); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(devicestate.AllocatableDevices)
		}
	}

	return r0
}

// MockDeviceStateIface_GetAllocatableDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllocatableDevices'
type MockDeviceStateIface_GetAllocatableDevices_Call struct {
	*mock.Call
}

// GetAllocatableDevices is a helper method to define mock.On call
func (_e *MockDeviceStateIface_Expecter) GetAllocatableDevices() *MockDeviceStateIface_GetAllocatableDevices_Call {
	return &MockDeviceStateIface_GetAllocatableDevices_Call{Call: _e.mock.On("GetAllocatableDevices")}
}

func (_c *MockDeviceStateIface_GetAllocatableDevices_Call) Run(run func()) *MockDeviceStateIface_GetAllocatableDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceStateIface_GetAllocatableDevices_Call) Return(_a0 devicestate.AllocatableDevices) *MockDeviceStateIface_GetAllocatableDevices_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeviceStateIface_GetAllocatableDevices_Call) RunAndReturn(run func() devicestate.AllocatableDevices) *MockDeviceStateIface_GetAllocatableDevices_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareResourceClaim provides a mock function with given fields: ctx, claim
func (_m *MockDeviceStateIface) PrepareResourceClaim(ctx context.Context, claim *v1.ResourceClaim) ([]*types.PreparedDevice, error) {
	ret := _m.Called(ctx, claim)

	if len(ret) == 0 {
		panic("no return value specified for PrepareResourceClaim")
	}

	var r0 []*types.PreparedDevice
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ResourceClaim) ([]*types.PreparedDevice, error)); ok {
		return rf(ctx, claim)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ResourceClaim) []*types.PreparedDevice); ok {
		r0 = rf(ctx, claim)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.PreparedDevice)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.ResourceClaim) error); ok {
		r1 = rf(ctx, claim)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeviceStateIface_PrepareResourceClaim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareResourceClaim'
type MockDeviceStateIface_PrepareResourceClaim_Call struct {
	*mock.Call
}

// PrepareResourceClaim is a helper method to define mock.On call
//   - ctx context.Context
//   - claim *v1.ResourceClaim
func (_e *MockDeviceStateIface_Expecter) PrepareResourceClaim(ctx interface{}, claim interface{}) *MockDeviceStateIface_PrepareResourceClaim_Call {
	return &MockDeviceStateIface_PrepareResourceClaim_Call{Call: _e.mock.On("PrepareResourceClaim", ctx, claim)}
}

func (_c *MockDeviceStateIface_PrepareResourceClaim_Call) Run(run func(ctx context.Context, claim *v1.ResourceClaim)) *MockDeviceStateIface_PrepareResourceClaim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.ResourceClaim))
	})
	return _c
}

func (_c *MockDeviceStateIface_PrepareResourceClaim_Call) Return(_a0 []*types.PreparedDevice, _a1 error) *MockDeviceStateIface_PrepareResourceClaim_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeviceStateIface_PrepareResourceClaim_Call) RunAndReturn(run func(context.Context, *v1.ResourceClaim) ([]*types.PreparedDevice, error)) *MockDeviceStateIface_PrepareResourceClaim_Call {
	_c.Call.Return(run)
	return _c
}

// SetRepublishCallback provides a mock function with given fields: callback
func (_m *MockDeviceStateIface) SetRepublishCallback(callback func(context.Context) error) {
	_m.Called(callback)
}

// MockDeviceStateIface_SetRepublishCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRepublishCallback'
type MockDeviceStateIface_SetRepublishCallback_Call struct {
	*mock.Call
}

// SetRepublishCallback is a helper method to define mock.On call
//   - callback func(context.Context) error
func (_e *MockDeviceStateIface_Expecter) SetRepublishCallback(callback interface{}) *MockDeviceStateIface_SetRepublishCallback_Call {
	return &MockDeviceStateIface_SetRepublishCallback_Call{Call: _e.mock.On("SetRepublishCallback", callback)}
}

func (_c *MockDeviceStateIface_SetRepublishCallback_Call) Run(run func(callback func(context.Context) error)) *MockDeviceStateIface_SetRepublishCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(context.Context) error))
	})
	return _c
}

func (_c *MockDeviceStateIface_SetRepublishCallback_Call) Return() *MockDeviceStateIface_SetRepublishCallback_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDeviceStateIface_SetRepublishCallback_Call) RunAndReturn(run func(func(context.Context) error)) *MockDeviceStateIface_SetRepublishCallback_Call {
	_c.Run(run)
	return _c
}

// UnprepareResourceClaim provides a mock function with given fields: ctx, preparedDevices
func (_m *MockDeviceStateIface) UnprepareResourceClaim(ctx context.Context, preparedDevices []*types.PreparedDevice) error {
	ret := _m.Called(ctx, preparedDevices)

	if len(ret) == 0 {
		panic("no return value specified for UnprepareResourceClaim")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*types.PreparedDevice) error); ok {
		r0 = rf(ctx, preparedDevices)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeviceStateIface_UnprepareResourceClaim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnprepareResourceClaim'
type MockDeviceStateIface_UnprepareResourceClaim_Call struct {
	*mock.Call
}

// UnprepareResourceClaim is a helper method to define mock.On call
//   - ctx context.Context
//   - preparedDevices []*types.PreparedDevice
func (_e *MockDeviceStateIface_Expecter) UnprepareResourceClaim(ctx interface{}, preparedDevices interface{}) *MockDeviceStateIface_UnprepareResourceClaim_Call {
	return &MockDeviceStateIface_UnprepareResourceClaim_Call{Call: _e.mock.On("UnprepareResourceClaim", ctx, preparedDevices)}
}

func (_c *MockDeviceStateIface_UnprepareResourceClaim_Call) Run(run func(ctx context.Context, preparedDevices []*types.PreparedDevice)) *MockDeviceStateIface_UnprepareResourceClaim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*types.PreparedDevice))
	})
	return _c
}

func (_c *MockDeviceStateIface_UnprepareResourceClaim_Call) Return(_a0 error) *MockDeviceStateIface_UnprepareResourceClaim_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeviceStateIface_UnprepareResourceClaim_Call) RunAndReturn(run func(context.Context, []*types.PreparedDevice) error) *MockDeviceStateIface_UnprepareResourceClaim_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeviceStateIface creates a new instance of MockDeviceStateIface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceStateIface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceStateIface {
	mock := &MockDeviceStateIface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
